### ISSUE TITLE
Not Compatible with MomentJS 2.9+

### ISSUE THREAD

**Issue by ddelella** [atais/angular-eonasdan-datetimepicker#33]
If you run the plugin with any version of momentjs after 2.9+ the browser will produce a warning similar to the message below.  I was using the format "hh:mm A" which is a valid ISO format according to the latest momentjs documentation.

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:2710)
    at oa (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:10865)
    at Ia (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:14772)
    at Ha (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:14633)
    at Ga (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:14353)
    at Ja (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:15085)
    at Ka (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:15119)
    at a (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js:6:202)
    at Og.a.$render (https://rawgit.com/atais/angular-eonasdan-datetimepicker/0.3.8/dist/angular-eonasdan-datetimepicker.min.js:1:468)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.min.js:286:500

**Comment by ddelella** [comment]
NOTE: the error above was found in the Chrome developer console using the simple example off the main page.
