### ISSUE TITLE
How to close the datetimepicker after selection of time

### ISSUE THREAD

**Issue by chaluvadis** [atais/angular-eonasdan-datetimepicker#36]
hey how to close the datetime picker after selection of time, I tried using autoClose: true and autoclose: true, 
when ever I use the auto close option i am getting the following errors.

`angular.js:13642 TypeError: option autoclose is not recognized!
    at Boolean.<anonymous> (https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js:8:22416)
    at Function.each (https://code.jquery.com/jquery-2.2.4.min.js:2:2911)
    at Object.l.options (https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js:8:22372)
    at c (https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js:9:2055)
    at HTMLDivElement.<anonymous> (https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js:9:2427)
    at Function.each (https://code.jquery.com/jquery-2.2.4.min.js:2:2861)
    at n.fn.init.each (https://code.jquery.com/jquery-2.2.4.min.js:2:845)
    at n.fn.init.a.fn.datetimepicker (https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js:9:2297)
    at Object.link (https://rawgit.com/atais/angular-eonasdan-datetimepicker/0.3.8/dist/angular-eonasdan-datetimepicker.min.js:1:904)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.min.js:16:230 <div class="input-group ng-pristine ng-untouched ng-valid ng-isolate-scope" datetimepicker="" on-change="vm.update(vm.dateFrom, vm.dateTo)" ng-model="vm.dateTo" options="vm.optionsTo">`

`angular.js:13642 TypeError: Cannot read property 'date' of undefined
    at Og.a.$render (VM579 angular-eonasdan-datetimepicker.min.js:1)
    at VM576 angular.min.js:286
    at m.$digest (VM576 angular.min.js:142)
    at m.$apply (VM576 angular.min.js:145)
    at VM576 angular.min.js:21
    at Object.invoke (VM576 angular.min.js:41)
    at c (VM576 angular.min.js:21)
    at Ac (VM576 angular.min.js:21)
    at fe (VM576 angular.min.js:20)
    at HTMLDocument.<anonymous> (VM576 angular.min.js:315)`
`TypeError: Cannot read property 'format' of undefined
    at VM579 angular-eonasdan-datetimepicker.min.js:1
    at Function.map (VM573 jquery-2.2.4.min.js:2)
    at VM579 angular-eonasdan-datetimepicker.min.js:1
    at m.$digest (VM576 angular.min.js:142)
    at m.$apply (VM576 angular.min.js:145)
    at VM576 angular.min.js:21
    at Object.invoke (VM576 angular.min.js:41)
    at c (VM576 angular.min.js:21)
    at Ac (VM576 angular.min.js:21)
    at fe (VM576 angular.min.js:20)`

![error](https://user-images.githubusercontent.com/738511/34835417-58d08606-f6ba-11e7-8215-13f8eaa20fb0.PNG)

Following is my scope with options 

$scope.options = {
                        format: 'MM/DD/YYYY hh:mm A',
                        sideBySide: true,
                       autoclose: true
                    }

my html to render the datetime picker.
`<div class="form-group">
                        <div class="input-group">
                            <input name="eventstartdate" id="eventstartdate" class="form-control"
                                   datetimepicker data-ng-model="event.eventstartdatetime" options="options">
                            <span class="input-group-addon span-date-icon">
                                <i class="fa fa-calendar"></i>
                            </span>
                        </div>
               </div>`

any help appreciated.

**Comment by atais** [comment]
There is no `autoclose` option in http://eonasdan.github.io/bootstrap-datetimepicker/Options/
so this is not supported.

I think you want this one: http://eonasdan.github.io/bootstrap-datetimepicker/Options/#keepopen

**Comment by artsnr1** [comment]
KeepOpen option also isn't working. And by default it should auto close
